# PostgreSQL. Versions 9.3+ are supported.
#
# Install the pg driver:
#   gem install pg
# On macOS with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem "pg"
#
# 目的:
#   - 開発/テストはローカル PostgreSQL に接続
#   - 本番（Render）は DATABASE_URL ひとつで接続（単一DB）
#   - 本番は default を継承せず、ローカル用の host: localhost 等が混入しないようにする
#
# 備考:
#   - Render の Postgres を使う場合、DATABASE_URL の末尾に `?sslmode=require`
#     を付与すると接続が安定します（例: postgres://USER:PASS@HOST:PORT/DB?sslmode=require）。
#   - プールサイズは RAILS_MAX_THREADS で調整できます。

# ------------------------------------------------------------
# 共通（ローカル向けのデフォルト値）
# ------------------------------------------------------------
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide:
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # ---- Local connection defaults (explicit) ----
  # ローカルの Postgres に接続するためのデフォルト値を明示します。
  # 開発・テストではこの値を継承します（本番は継承しません）。
  host: localhost      # ← ローカルのホスト名
  port: 5432           # ← Postgres のデフォルトポート
  # username: postgres   # ← ローカルの PG ユーザー名（必要に応じて変更）
  password:            # ← ローカルにパスワードがある場合は記入


# ------------------------------------------------------------
# 開発
# ------------------------------------------------------------
development:
  <<: *default
  database: task_master_development

  # The specified database role being used to connect to PostgreSQL.
  # To create additional roles in PostgreSQL see `$ createuser --help`.
  # When left blank, PostgreSQL will use the default role. This is
  # the same name as the operating system user running Rails.
  # username: task_master

  # The password associated with the PostgreSQL role (username).
  # password:

  # Connect on a TCP socket. Omitted by default since the client uses a
  # domain socket that doesn't need configuration. Windows does not have
  # domain sockets, so uncomment these lines.
  # host: localhost

  # The TCP port the server listens on. Defaults to 5432.
  # If your server runs on a different port number, change accordingly.
  # port: 5432

  # Schema search path. The server defaults to $user,public
  # schema_search_path: myapp,sharedapp,public

  # Minimum log levels, in increasing order:
  #   debug5, debug4, debug3, debug2, debug1,
  #   log, notice, warning, error, fatal, and panic
  # Defaults to warning.
  # min_messages: notice


# ------------------------------------------------------------
# テスト
# ------------------------------------------------------------
test:
  <<: *default
  database: task_master_test


# ------------------------------------------------------------
# 本番（Render）— 単一DB構成（Solid Cable 対応）
#
# 重要：
#   - Rails 8（Solid Cable/Action Cable）が `production.cable` を参照するため、
#     `production:` の下を複数DB形式（primary / cable）で定義します。
#   - どちらも同じ DATABASE_URL を使います（必要に応じて将来分離可）。
#   - default は継承しません（ローカル向け host: や port: が混ざらないようにするため）。
# ------------------------------------------------------------
production:
  primary: &primary_production
    adapter: postgresql
    url: <%= ENV.fetch("DATABASE_URL") %>  # 例: postgres://USER:PASS@HOST:PORT/DB?sslmode=require
    pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  # Rails 8 の Action Cable（solid_cable）用。単一DB運用なので primary を継承。
  cable:
    <<: *primary_production
    # 必要に応じて個別に上書き可（例：pool: 5 など）
    # pool: 5

# 参考（使わない例：従来の単一定義）
# production:
#   url: <%= ENV.fetch("DATABASE_URL") %>
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   # この単一定義では `production.cable` が存在せず、Rails 8 では起動時にエラーになります。
